# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pz < Formula
  desc "A project-zer0/pz launcher"
  homepage "https://github.com/project-zer0/pz-launcher"
  version "0.1.2"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/project-zer0/pz-launcher/releases/download/0.1.2/pz-launcher_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "cf4cd423109ccd10f75dc2ffce587bb1f9822340aeab2e49256a3c8236fbdd37"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/project-zer0/pz-launcher/releases/download/0.1.2/pz-launcher_0.1.2_Linux_x86_64.tar.gz"
    sha256 "f7bb65bdc48637f4859159364e8dc0e6b4efd0a64341a909ff6bd985d26dd607"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/project-zer0/pz-launcher/releases/download/0.1.2/pz-launcher_0.1.2_Linux_arm64.tar.gz"
    sha256 "6797deac2a2382444ffa6bb1c659de977b07eba3d81c1918798d59961dff9ec1"
  end

  head "https://github.com/project-zer0/pz-launcher.git"

  def install
    bin.install "pz"
  end
end
