# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pz < Formula
  desc "A project-zer0/pz launcher"
  homepage "https://github.com/project-zer0/pz-launcher"
  version "0.1.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/project-zer0/pz-launcher/releases/download/0.1.3/pz-launcher_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "9b91b88375a12433e42b3152fc4a4235db760cfe93ac275dbb2148d13a152f9f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/project-zer0/pz-launcher/releases/download/0.1.3/pz-launcher_0.1.3_Linux_x86_64.tar.gz"
    sha256 "74ac0e977426b550a1a012989fc3174c20978fb619e47212fbbcd7d1b4c31b87"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/project-zer0/pz-launcher/releases/download/0.1.3/pz-launcher_0.1.3_Linux_arm64.tar.gz"
    sha256 "89dbea1ab424549b856384293582d3a75461623be3ddb23716fe183c7b7a39d6"
  end

  head "https://github.com/project-zer0/pz-launcher.git"

  def install
    bin.install "pz"
  end
end
